// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDxPqd0elt99twtMADykPMSh7_B21k4G8',
    appId: '1:249516350954:web:5fd9805864101595ffe693',
    messagingSenderId: '249516350954',
    projectId: 'parichay-flutter',
    authDomain: 'parichay-flutter.firebaseapp.com',
    storageBucket: 'parichay-flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPaPig5tf811_psKjqChYsVZVJ812CarI',
    appId: '1:249516350954:android:b77ded6efbc4481effe693',
    messagingSenderId: '249516350954',
    projectId: 'parichay-flutter',
    storageBucket: 'parichay-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_r4X1IA35xB2nbSkBfzH5lBO9Trml0Pg',
    appId: '1:249516350954:ios:2067684dbdb46dbfffe693',
    messagingSenderId: '249516350954',
    projectId: 'parichay-flutter',
    storageBucket: 'parichay-flutter.appspot.com',
    iosBundleId: 'com.example.parichay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_r4X1IA35xB2nbSkBfzH5lBO9Trml0Pg',
    appId: '1:249516350954:ios:cf6acd84a1ac49b3ffe693',
    messagingSenderId: '249516350954',
    projectId: 'parichay-flutter',
    storageBucket: 'parichay-flutter.appspot.com',
    iosBundleId: 'com.example.parichay.RunnerTests',
  );
}
